/**
 * VantaDB — Competitive benchmark JSON contract (INV-007-B).
 *
 * Single source of truth for the /benchmarks competitive table.
 * The versioned JSON (`web/src/lib/data/competitive-benchmark.json`) is
 * regenerated by `benchmarks/competitive_bench.py --json-output <path>`.
 * No numbers are hardcoded here — this file only types and re-exports the JSON.
 */
import competitiveBenchmark from "./data/competitive-benchmark.json";

export interface CompetitiveBenchmarkResult {
  engine: string;
  ingest_qps: number;
  index_time_ms: number | null; // null => "N/A (incremental)" e.g. ChromaDB
  query_qps: number;
  query_p50_ms: number;
  query_p99_ms: number;
  recall_at_k: number; // fraction 0..1
  mem_peak_rss_mb: number;
  mem_delta_rss_mb: number;
}

export interface CompetitiveBenchmark {
  schema_version: number;
  generated_by: string;
  generated_at: string;
  source: string;
  hardware: {
    note: string;
    os: string | null;
    cpu_count: number | null;
    cpu_model: string | null;
    python: string | null;
  };
  versions: Record<string, string | null>;
  dataset: {
    name: string;
    metric: string;
    vectors: number;
    queries: number;
    top_k: number;
    ingest_mode: string;
  };
  methodology: {
    iterations_per_engine: number;
    aggregation: string;
    ground_truth: string;
    warmup_queries: number;
  };
  results: CompetitiveBenchmarkResult[];
}

export const COMPETITIVE_BENCHMARK = competitiveBenchmark as unknown as CompetitiveBenchmark;